rootProject.name = "Note App"
include (":app")
include(":core:components")
include(":task")
include(":task:task-list")
include(":core:resource")
include(":core")
include(":core:constance")
include(":core:data")
include(":task:data")
include(":task:domain")
include(":task:task-components")
include(":task:task-add-edit")
include(":core:state-manager")
