rootProject.name = "Note App"
include (":app")
include(":components")
include(":task")
include(":task:task-list")
include(":resource")
include(":core")
include(":core:constance")
include(":data")
include(":task:data")
include(":task:domain")
